arsapps_module.settings:
  type: config_object
  label: 'ARSApps Module settings'
  mapping:
    example_text:
      type: text
      label: 'Example text field'
    example_number:
      type: integer
      label: 'Example number field'
    example_boolean:
      type: boolean
      label: 'Example boolean field'
    example_array:
      type: sequence
      label: 'Example array field'
      sequence:
        type: string